ALTER TABLE HISTORICO_VIDA_UTIL DROP FOREIGN KEY FK_HISTORICO_VIDA_UTIL_COD_FONTE_DADO
ALTER TABLE ALARME DROP FOREIGN KEY FK_ALARME_COD_FONTE_DADO
ALTER TABLE COMPORTAMENTO DROP FOREIGN KEY UNQ_COMPORTAMENTO_0
ALTER TABLE COMPONENTE DROP FOREIGN KEY FK_COMPONENTE_ITEM_CODIGO
ALTER TABLE COMPONENTE DROP FOREIGN KEY UNQ_COMPONENTE_0
ALTER TABLE META_DADOS DROP FOREIGN KEY FK_META_DADOS_TIPO
ALTER TABLE META_DADOS DROP FOREIGN KEY UNQ_META_DADOS_0
ALTER TABLE FONTE_DADO DROP FOREIGN KEY FK_FONTE_DADO_FILA
ALTER TABLE FONTE_DADO DROP FOREIGN KEY FK_FONTE_DADO_COD_COMPONENTE
ALTER TABLE FONTE_DADO DROP FOREIGN KEY FK_FONTE_DADO_CODIGO
ALTER TABLE FONTE_DADO DROP FOREIGN KEY FK_FONTE_DADO_LOCALIZACAO
ALTER TABLE HISTORICO DROP FOREIGN KEY FK_HISTORICO_COD_FONTE_DADO
ALTER TABLE UNIDADE_GERADORA DROP FOREIGN KEY FK_UNIDADE_GERADORA_COD_USINA
ALTER TABLE UNIDADE_GERADORA DROP FOREIGN KEY UNQ_UNIDADE_GERADORA_0
ALTER TABLE LOCALIZACAO DROP FOREIGN KEY UNQ_LOCALIZACAO_0
ALTER TABLE MEDIDA_ADQUIRIDA_BRUTA DROP FOREIGN KEY FK_MEDIDA_ADQUIRIDA_BRUTA_COD_FONTE_DADO
ALTER TABLE USINA DROP FOREIGN KEY UNQ_USINA_0
ALTER TABLE FILA DROP FOREIGN KEY UNQ_FILA_0
ALTER TABLE ARQUIVO_DADOS_BRUTOS DROP FOREIGN KEY FK_ARQUIVO_DADOS_BRUTOS_COD_FONTE_DADO
ALTER TABLE INDICE_DADOS_BRUTOS DROP FOREIGN KEY FK_INDICE_DADOS_BRUTOS_COD_FONTE_DADO
ALTER TABLE AGENDAMENTO_USUARIO DROP FOREIGN KEY FK_AGENDAMENTO_USUARIO_CODIGO_REQUISICAO
ALTER TABLE AGENDAMENTO_USUARIO DROP FOREIGN KEY FK_AGENDAMENTO_USUARIO_CODIGO_MAB
ALTER TABLE SOLICITACAO_AGENDAMENTO DROP FOREIGN KEY FK_SOLICITACAO_AGENDAMENTO_COD_ALARME
ALTER TABLE SOLICITACAO_AGENDAMENTO DROP FOREIGN KEY UNQ_SOLICITACAO_AGENDAMENTO_0
ALTER TABLE COMPORTAMENTO_META DROP FOREIGN KEY FK_COMPORTAMENTO_META_COD_COMPORTAMENTO
ALTER TABLE COMPORTAMENTO_META DROP FOREIGN KEY FK_COMPORTAMENTO_META_COD_FONTE_META
ALTER TABLE TIPO_FONTE_DADO DROP FOREIGN KEY FK_TIPO_FONTE_DADO_COD_GRANDEZA
ALTER TABLE TIPO_FONTE_DADO DROP FOREIGN KEY UNQ_TIPO_FONTE_DADO_0
ALTER TABLE GRANDEZA DROP FOREIGN KEY UNQ_GRANDEZA_0
ALTER TABLE USUARIO DROP FOREIGN KEY UNQ_USUARIO_0
ALTER TABLE APLICACAO DROP FOREIGN KEY UNQ_APLICACAO_0
ALTER TABLE FUNCIONALIDADE DROP FOREIGN KEY FK_FUNCIONALIDADE_COD_APLICACAO
ALTER TABLE FUNCIONALIDADE DROP FOREIGN KEY UNQ_FUNCIONALIDADE_0
ALTER TABLE TEM_OCORRENCIA DROP FOREIGN KEY UNQ_TEM_OCORRENCIA_0
ALTER TABLE DETALHE_OCORRENCIA DROP FOREIGN KEY UNQ_DETALHE_OCORRENCIA_0
ALTER TABLE VIDA_RESIDUAL_MEDIDA DROP FOREIGN KEY FK_VIDA_RESIDUAL_MEDIDA_COD_SERIES
ALTER TABLE VIDA_RESIDUAL_SERIES DROP FOREIGN KEY FK_VIDA_RESIDUAL_SERIES_COD_VIDA_META
ALTER TABLE VIDA_RESIDUAL_META DROP FOREIGN KEY FK_VIDA_RESIDUAL_META_CODIGO
ALTER TABLE ABS_ARVORE_FOLHA DROP FOREIGN KEY FK_ABS_ARVORE_FOLHA_PAI
ALTER TABLE ABS_ARVORE_NO DROP FOREIGN KEY FK_ABS_ARVORE_NO_CODIGO
ALTER TABLE ARVORE_FOLHA DROP FOREIGN KEY FK_ARVORE_FOLHA_CODIGO
ALTER TABLE ARVORE_NO DROP FOREIGN KEY FK_ARVORE_NO_CODIGO
ALTER TABLE HISTORICO_META DROP FOREIGN KEY FK_HISTORICO_META_CODIGO
ALTER TABLE HISTORICO_META DROP FOREIGN KEY FK_HISTORICO_META_COD_FONTE_DADO
ALTER TABLE HISTORICO_SERIES DROP FOREIGN KEY FK_HISTORICO_SERIES_COD_HIST_META
ALTER TABLE HISTORICO_MEDIDA DROP FOREIGN KEY FK_HISTORICO_MEDIDA_COD_HIST_SERIES
ALTER TABLE GRUPO_USUARIO DROP FOREIGN KEY FK_GRUPO_USUARIO_COD_GRUPO
ALTER TABLE GRUPO_USUARIO DROP FOREIGN KEY FK_GRUPO_USUARIO_COD_USUARIO
ALTER TABLE PERMISSAO_APLICACAO DROP FOREIGN KEY FK_PERMISSAO_APLICACAO_COD_APLICACAO
ALTER TABLE PERMISSAO_APLICACAO DROP FOREIGN KEY FK_PERMISSAO_APLICACAO_COD_GRUPO
ALTER TABLE PERMISSAO_FUNCIONALIDADE DROP FOREIGN KEY FK_PERMISSAO_FUNCIONALIDADE_COD_FUNCIONALIDADE
ALTER TABLE PERMISSAO_FUNCIONALIDADE DROP FOREIGN KEY FK_PERMISSAO_FUNCIONALIDADE_COD_GRUPO
DROP TABLE RELATORIO
DROP TABLE HISTORICO_VIDA_UTIL
DROP TABLE ALARME
DROP TABLE COMPORTAMENTO
DROP TABLE COMPONENTE
DROP TABLE META_DADOS
DROP TABLE FONTE_DADO
DROP TABLE HISTORICO
DROP TABLE UNIDADE_GERADORA
DROP TABLE LOCALIZACAO
DROP TABLE MEDIDA_ADQUIRIDA_BRUTA
DROP TABLE USINA
DROP TABLE FILA
DROP TABLE ARQUIVO_DADOS_BRUTOS
DROP TABLE INDICE_DADOS_BRUTOS
DROP TABLE MEDICOES_VALIDACAO_SADM
DROP TABLE AGENDAMENTO_USUARIO
DROP TABLE SOLICITACAO_AGENDAMENTO
DROP TABLE VIEW_TREE
DROP TABLE COMPORTAMENTO_META
DROP TABLE HISTOGRAMA_VENTO
DROP TABLE MODELO_CONDUTOR
DROP TABLE STOCKBRIDGE
DROP TABLE STOCKBRIDGE_EXP
DROP TABLE TIPO_FONTE_DADO
DROP TABLE GRANDEZA
DROP TABLE USUARIO
DROP TABLE GRUPO
DROP TABLE APLICACAO
DROP TABLE FUNCIONALIDADE
DROP TABLE TEM_OCORRENCIA
DROP TABLE DETALHE_OCORRENCIA
DROP INDEX SOMA_RL_META_TIME_INDEX ON VIDA_RESIDUAL_MEDIDA
DROP TABLE VIDA_RESIDUAL_MEDIDA
DROP TABLE VIDA_RESIDUAL_SERIES
DROP TABLE VIDA_RESIDUAL_META
DROP TABLE ABS_ARVORE_FOLHA
DROP TABLE ABS_ARVORE_NO
DROP TABLE ARVORE_FOLHA
DROP TABLE ARVORE_NO
DROP TABLE HISTORICO_META
DROP TABLE HISTORICO_SERIES
DROP INDEX SOMA_HIST_SERIES_TIME_INDEX ON HISTORICO_MEDIDA
DROP TABLE HISTORICO_MEDIDA
DROP TABLE GRUPO_USUARIO
DROP TABLE PERMISSAO_APLICACAO
DROP TABLE PERMISSAO_FUNCIONALIDADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
